
config default

# waybar has an additional field for the style (2 configs)
default.waybar style = "default-style.css"
default.waybar = "default-style.css"

default.sway = "default-config"

default.nvim = "default-init.lua"

default.btop = "default-btop.conf"


path.sway = "~/.config/sway/"
path.btop = "~/.config/btop/"
path.nvim = "~/.config/nvim/"
